
# SEO settings
title: UIST勉強会
description: "UIST勉強会のお知らせページです"
keywords: "UIST, ACM, 勉強会"
url: 
# baseurl: "/simplest"
baseurl: null

# google_analytics: UA-52446115-1
# repo: http://github.com/nandomoreirame/simplest
# disqus_shortname: "nandothemes"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

google_analytics: UA-113054721-1

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : UIST勉強会
  job      : 
  bio      : 
  thumb    : 
  email    : 
  url      : 
  github   : 
  twitter  : 
  facebook : 
  linkedin : 

# social settings
og_locale: "ja_JP"
# twitter_card: "summary_large_image"
# twitter_site: "@nandomoreirame"

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
